"""empty message

Revision ID: 20a828b370b0
Revises: 751a9194e24d
Create Date: 2021-01-28 16:32:15.371441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a828b370b0'
down_revision = '751a9194e24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'paper_type', ['paperType'])
    op.alter_column('print_order', 'paperSize',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('print_order', 'paperType',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('print_order', 'printProduct',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('print_order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'print_order', 'paper_size', ['paperSize'], ['id'])
    op.create_foreign_key(None, 'print_order', 'paper_type', ['paperType'], ['id'])
    op.create_foreign_key(None, 'print_order', 'print_product', ['printProduct'], ['id'])
    op.create_unique_constraint(None, 'print_product', ['design'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'print_product', type_='unique')
    op.drop_constraint(None, 'print_order', type_='foreignkey')
    op.drop_constraint(None, 'print_order', type_='foreignkey')
    op.drop_constraint(None, 'print_order', type_='foreignkey')
    op.alter_column('print_order', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('print_order', 'printProduct',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('print_order', 'paperType',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('print_order', 'paperSize',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'paper_type', type_='unique')
    # ### end Alembic commands ###
