"""empty message

Revision ID: 28faef8ccd35
Revises: 
Create Date: 2021-01-31 14:46:18.893093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28faef8ccd35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paperSize', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paperType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paperType')
    )
    op.create_table('print_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design')
    )
    roles_table = op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('print_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('paperSize', sa.Integer(), nullable=False),
    sa.Column('paperType', sa.Integer(), nullable=False),
    sa.Column('printProduct', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paperSize'], ['paper_size.id'], ),
    sa.ForeignKeyConstraint(['paperType'], ['paper_type.id'], ),
    sa.ForeignKeyConstraint(['printProduct'], ['print_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('paperSize', sa.Integer(), nullable=False),
    sa.Column('paperType', sa.Integer(), nullable=False),
    sa.Column('printProduct', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paperSize'], ['paper_size.id'], ),
    sa.ForeignKeyConstraint(['paperType'], ['paper_type.id'], ),
    sa.ForeignKeyConstraint(['printProduct'], ['print_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(roles_table,
                   [
                       {'name': 'admin'},
                       {'name': 'weirdo'}
                   ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('print_order_history')
    op.drop_table('print_order')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('print_product')
    op.drop_table('paper_type')
    op.drop_table('paper_size')
    # ### end Alembic commands ###
