"""empty message

Revision ID: 32c6c5ec8806
Revises: 
Create Date: 2021-01-21 16:00:39.480402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c6c5ec8806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paperSize', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paperType', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=True),
    sa.Column('paperSize', sa.Integer(), nullable=True),
    sa.Column('paperType', sa.Integer(), nullable=True),
    sa.Column('printProduct', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_product')
    op.drop_table('print_order')
    op.drop_table('paper_type')
    op.drop_table('paper_size')
    # ### end Alembic commands ###
