"""empty message

Revision ID: 90468b50ba1a
Revises: 28faef8ccd35
Create Date: 2021-02-06 19:59:22.817225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90468b50ba1a'
down_revision = '28faef8ccd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printProduct', sa.Integer(), nullable=False),
    sa.Column('paperSize', sa.Integer(), nullable=False),
    sa.Column('paperType', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paperSize'], ['paper_size.id'], ),
    sa.ForeignKeyConstraint(['paperType'], ['paper_type.id'], ),
    sa.ForeignKeyConstraint(['printProduct'], ['print_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_inventory')
    # ### end Alembic commands ###
